spring:
  profiles:
    active: support, security, system
pengsoft:
  security:
    oauth:
      authorization-server-enabled: true
      resource-server-enabled: true
      clients:
        - id: pengsoft
          secret: pengsoft
          access-token-validity-seconds: 2592000
          grant-types:
            - password  