spring:
  profiles:
    active: support, security, system, basedata
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
pengsoft:
  security:
    oauth:
      authorization-server-enabled: true
      resource-server-enabled: true
      clients:
        - id: pengsoft
          secret: pengsoft
          access-token-validity-seconds: 2592000
          grant-types:
            - password  